frontend/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'user/', views.user, name='user'),
  url(r'stop/add/$', views.BusStopCreate.as_view(), name='stop-add'),
]

madapi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from oauth2_provider.decorators import protected_resource

from graphene_django.views import GraphQLView
from oauth2_provider.views.generic import ProtectedResourceView
import oauth2_provider.views as oauth2_views

class AuthGraphQLView(ProtectedResourceView, GraphQLView):
    pass

oauth2_endpoint_views = [
    url(r'^authorize/$', oauth2_views.AuthorizationView.as_view(), name="authorize"),
    url(r'^token/$', oauth2_views.TokenView.as_view(), name="token"),
    url(r'^revoke-token/$', oauth2_views.RevokeTokenView.as_view(), name="revoke-token"),
]

if settings.DEBUG:
    # OAuth2 Application Management endpoints
    oauth2_endpoint_views += [
        url(r'^applications/$', oauth2_views.ApplicationList.as_view(), name="list"),
        url(r'^applications/register/$', oauth2_views.ApplicationRegistration.as_view(), name="register"),
        url(r'^applications/(?P<pk>\d+)/$', oauth2_views.ApplicationDetail.as_view(), name="detail"),
        url(r'^applications/(?P<pk>\d+)/delete/$', oauth2_views.ApplicationDelete.as_view(), name="delete"),
        url(r'^applications/(?P<pk>\d+)/update/$', oauth2_views.ApplicationUpdate.as_view(), name="update"),
    ]

    # OAuth2 Token Management endpoints
    oauth2_endpoint_views += [
        url(r'^authorized-tokens/$', oauth2_views.AuthorizedTokensListView.as_view(), name="authorized-token-list"),
        url(r'^authorized-tokens/(?P<pk>\d+)/delete/$', oauth2_views.AuthorizedTokenDeleteView.as_view(),
            name="authorized-token-delete"),
    ]


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^graphql', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    url(r'^graphqlapi', AuthGraphQLView.as_view(graphiql=True)),
    # DOT urls
    url(r'^o/', include(oauth2_endpoint_views, namespace='oauth2_provider')),
    url(r'^', include('frontend.urls')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from allauth.account.models import EmailAddress

import hashlib

# largely swiped from here:
# https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html
# and 
# http://www.sarahhagstrom.com/2013/09/the-missing-django-allauth-tutorial/
# Create your models here.



class Profile(models.Model):
    user = models.OneToOneField(User, related_name="profile")
    address = models.CharField(blank=True, max_length=200)
    parcel = models.CharField(blank=True, max_length=50)
    trashpickup = models.CharField(blank=True, max_length=200)

    def __str__(self):
      return str(self.user.username)    

    def account_verified(self):
      """
      If the user is logged in and has verified hisser email address, return True,
      otherwise return False
      """
      result = EmailAddress.objects.filter(email=self.user.email)
      if len(result):
         return result[0].verified
      return False

    def profile_image_url(self):
      """
      Return the URL for the user's Facebook icon if the user is logged in via Facebook,
      otherwise return the user's Gravatar URL
      """

      return "https://www.gravatar.com/avatar/{}?s=40".format(hashlib.md5(self.user.email.encode('utf-8')).hexdigest())

# TODO - lookup parcel from address
# the socrata api to do that looks like this
# 
# curl -v https://data.cityofmadison.com/resource/at89-xy89.json?\$where=upper\(address\)%20like%20upper\(%27%25202%20Demilo%20way%25%27\)
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


# this should really be a core set of stops that is managed by
# the app and then a user has a bunch of references to which stops 
# they like
#
# useful bus lookup - curl -v 'http://api.smsmybus.com/v1/getarrivals?key=XXXXX&stopID=1100'
class BusStop(models.Model):
    stop_id = models.CharField(blank=True, max_length=30)
    name = models.CharField(blank=True, max_length=200)
    default = models.BooleanField(default=False)
    owner = models.ForeignKey(Profile)

    def __str__(self):
      return str(self.name + "(" + self.stop_id + ")") 

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from django import forms
from core.models import BusStop, Profile

class BusStopForm(forms.ModelForm):
    class Meta:
        model = BusStop
        exclude = ('owner',)

core/views.py
from django.shortcuts import render

# Create your views here.

frontend/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
import json
from django.http import HttpResponse


from .forms import BusStopForm

from core.models import Profile, BusStop

def index(request):
    if request.user.is_authenticated():
      return render(request, "frontend/profile.html")
    else:
      return render(request, "frontend/index.html")

def user(request):
    if request.user.is_authenticated():
      data = {}
      data['username'] = request.user.username
      data['email'] = request.user.email
      data['firstname'] = request.user.first_name
      data['lastname'] = request.user.last_name
      data['id'] = request.user.pk
      return HttpResponse(json.dumps(data), content_type = "application/json")
    else:
      return HttpResponse('Unauthorized', status=401, content_type = "application/json")

class BusStopCreate(LoginRequiredMixin, CreateView):
  model = BusStop
  form_class = BusStopForm
  # why doesn't this template work?
  template_name = 'frontend/addstop.html'
  login_url = '/login'
  redirect_field_name = None

  # todo - S.O. note
  def form_valid(self, form):
      stop = form.save(commit=False)
      stop.owner = Profile.objects.get(user=self.request.user)  # use your own profile here
      stop.save()
      return HttpResponseRedirect(reverse_lazy('index'))

frontend/templates/frontend/addstop.html
{% extends 'frontend/base.html' %}
{% load bootstrap3 %}

{% block content %}

<div class="container">
    <div class="row">
      <div class="col-xs-12">
        <form role="form" method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% buttons submit='OK' reset="Clear" %}{% endbuttons %}
        </form>
     </div>
    </div>
</div>
{% endblock %}

frontend/templates/frontend/base.html
{% extends 'frontend/bootstrap.html' %}

{% load bootstrap3 %}

{% block bootstrap3_content %}
<style>
body {  padding-top: 70px;}
</style>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Code For Madison</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href={% url 'index' %}>Home</a></li>
            <li><a href="/about">About</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="/accounts/logout/">Logout<span class="sr-only">(current)</span></a></li>
            {% else %}
            <li><a href="/accounts/login/">Login<span class="sr-only">(current)</span></a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

   {% block content %}(no content){% endblock %}

{% endblock %}

frontend/templates/frontend/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}

{# see https://github.com/dyve/django-bootstrap3/blob/develop/bootstrap3/templates/bootstrap3/bootstrap3.html #}

{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}

frontend/templates/frontend/index.html
{% extends 'frontend/base.html' %}
{% load bootstrap3 %}

{% block content %}

    <div class="jumbotron">
      <div class="container">
        <h1>Welcome to Code for Madison</h1>
        <p>This is the landing page for Code For Madison's portal. Log in for more info</p>
      </div>
    </div>
{% endblock %}

frontend/templates/frontend/profile.html
{% extends 'frontend/base.html' %}
{% load bootstrap3 %}

{% block content %}

<div class="container">
    <div class="jumbotron">
        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

{% if user.is_authenticated %}
    <img src="{{ user.profile.profile_image_url }}"/>
    {% if user.first_name or user.last_name %}
        Here {{ request.user.first_name }} {{ request.user.last_name }}
    {% else %}
        {{ user.username }}
        <p> {{ user.profile.address }} </p>
    {% endif %}
    {% if user.profile.account_verified %} (verified) {% else %} (unverified) {% endif %}

{% else %}
    <a href="/accounts/login/" class="pull-right">Login</a>

{% endif %}
    </div>
    <div class="row">
    <div class="col-xs-12">
        {% for stop in user.profile.busstop_set.all %}
        <P>{{ stop }} </P>
        {% endfor %}
        <P><a href={% url 'stop-add' %}>Add another stop</a></P>
    </div>
</div>
{% endblock %}